Repository VBSquad/Androiders-Buddy, pull requests merged in 2020-10, with the labels that each got.

#101 Implemented Firebase Authentication
  Java/Firebase Authentication/Java/MainActivity.java
  Java/Firebase Authentication/Java/registerActivity.java
  Java/Firebase Authentication/Java/secondactivity.java
  Java/Firebase Authentication/SS/Screenshot_20200323-014343.png
  Java/Firebase Authentication/SS/Screenshot_20200323-014348.png
  Java/Firebase Authentication/XML/activity_main.xml
  Java/Firebase Authentication/XML/activity_register.xml
  Java/Firebase Authentication/XML/activity_secondactivity.xml
Labels: hacktoberfest

#102 Android Sensor
  Java/AndroidSensor/Java/MainActivity.java
  Java/AndroidSensor/Screenshots/screenshot.jpeg
  Java/AndroidSensor/XML/activitymain.xml
Labels: hacktoberfest

#108 Implemented Android Notification
  Java/Notification/Java/MainActivity.java
  Java/Notification/Java/NotificationView.java
  Java/Notification/Screenshots/android-notification2.png
  Java/Notification/Screenshots/android-notification3.png
  Java/Notification/Screenshots/info
  Java/Notification/XML/activity_main.xml
  Java/Notification/XML/activity_notification_view.xml
  Java/Notification/XML/strings.xml
Labels: hacktoberfest, hacktoberfest-accepted

#109 Implemented Android Text To Speech
  Java/TextToSpeech/java/MainActivity.java
  Java/TextToSpeech/screenshots/Screenshot_20201004-034300.png
  Java/TextToSpeech/screenshots/Screenshot_20201004-034313.png
  Java/TextToSpeech/xml/activity_main.xml
Labels: hacktoberfest, hacktoberfest-accepted

#114 UI-XML/RatingBar
  UI XML/RatingBar/readme.md
Labels: hacktoberfest-accepted

#116 Add hyperlinks
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
